# Generated by Django 5.1.6 on 2025-02-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефону')),
                ('pdf1', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('pdf2', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('pdf3', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('pdf4', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('pdf5', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
