# Generated by Django 5.1.6 on 2025-02-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_remove_fileupload_name_fileupload_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='email',
            field=models.EmailField(default='Невідомо', max_length=254, verbose_name='Електронна пошта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='middle_name',
            field=models.CharField(default='Невідомо', max_length=100, verbose_name='По батькові'),
            preserve_default=False,
        ),
    ]
