# Generated by Django 5.1.6 on 2025-02-19 08:24

import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_fileupload_email_alter_fileupload_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='pdf1',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='pdf2',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='pdf3',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='pdf4',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='pdf5',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='image_files',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[uploads.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='pdf_files',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', validators=[uploads.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='middle_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
